.TH PYSQL 1 "17 august 2006"
.SH NAME
pysql - command-line client for Oracle
.SH SYNOPSYS
pysql [options] [connection string]
.SH DESCRIPTION
Pysql is a free command-line interface to connect to an Oracle database. Pysql is an alternative for all those who suffer from sqlplus. It aims to bring confort and power to user without a heavy graphical application.
.SH OPTIONS
.TP
-h
shows help
.TP
-v
prints Pysql version
.TP
-L
exits if login attempt failed, instead of starting not connected
.TP
-S
sets silent mode which suppresses the dispay of banner, prompts and echoing of commands
.SH AUTHOR
Pysql was written by Sebastien Renard <sebastien.renard@digitalfox.org> and Sebastien Delcros <sebastien.delcros@gmail.com>.
.SH BUG REPORTS
If you find a bug in Pysql, please report it to the Pysql team <pysql@digitalfox.org>.
.SH COPYRIGHT
License GNU GPL version 3 <http://gnu.org/licenses/gpl.html>.
